version: "3.4"

services:
  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    volumes: ["./server:/server"]
    ports: ["8000:80"]
    environment: 
      - LOG_LEVEL=DEBUG
      - GUNICORN_reload=True
      - SB_CLIENT_ID=${SB_CLIENT_ID}
      - SB_SECRET=${SB_SECRET}
      - SB_API_VERSION=0
      - SB_REDIRECT_URL=http://localhost:8000/auth
      - SESSION_KEY=${SESSION_KEY}
