version: "3.4"

services:
  server:
    build: 
      context: .
      dockerfile: server/Dockerfile
    volumes: ["./server:/server"]
    ports: ["8000:80"]
    environment: 
      - GUNICORN_reload=True
